project_id = "fwkouvwabyftfhcsnfgm"

[functions.generate-ai-content]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.send-order-email]
verify_jwt = false

[functions.optimize-image]
verify_jwt = false

[functions.backup-data]
verify_jwt = true
